theme: jekyll-theme-dinky

# Added information below.
title: "Dharti Personal Portfolio"
description: "It is a personal portfolio of Dharti Madeka."

# Enables using emoji. See: https://help.github.com/en/articles/emoji-on-github-pages
plugins:
  - jemoji
